DEMO_INPUTS = [
    "SQL injection in login form",
    "Phishing email received",
    "Database port open",
    "Suspicious malware alert",
    "Ransomware note found",
    "DoS attack on web server",
    "Man-in-the-middle warning",
    "Weak password policy",
    "Open ports on firewall",
    "Possible data breach",
    "Login page accepts SQL payload",
    "User clicked phishing link",
    "Unknown executable downloaded",
    "Files encrypted on shared drive",
    "Website unavailable after traffic spike",
    "Certificate mismatch on banking site",
    "Admin password is easy to guess",
    "SSH port exposed to internet",
    "Customer records leaked",
    "Script injected in comment box",
    "Suspicious email asks for password",
    "Antivirus detected trojan",
    "Backup files are locked",
    "API endpoint flooded with requests",
    "Proxy detected unusual interception",
    "Default password still active",
    "Remote desktop port open",
    "Employee data exposed online",
    "Search box runs unsafe query",
    "Browser popup steals session token"
]
